#version 310 es
precision highp int;
// INSERT_FP32_BITS
layout(local_size_x=64) in;
layout(std430,binding=0) readonly buffer A {uint a[];};
layout(std430,binding=1) readonly buffer B {uint b[];};
layout(std430,binding=3) writeonly buffer O {uint o[];};
uniform uvec4 p;
void main() {
    uint i=gl_GlobalInvocationID.x;
    if(i>=p.x) return;
    o[2u*i]=add32(a[i],b[i]);o[2u*i+1u]=mul32(a[i],b[i]);
}
